// NInferMonitor
//
// This is free software; see the LICENSE.md file in the source distribution for precise wording.
//
// Copyright (C) 2026 Aleksey Sanin aleksey@aleksey.com. All Rights Reserved.

import { DarkButton } from "dark_button.slint";

export component AboutPanel inherits Rectangle {
    in property <string> version: "";

    callback close();

    background: #252526;
    border-radius: 6px;
    border-width: 1px;
    border-color: #3c3c3c;
    height: content-layout.preferred-height;

    click-blocker := TouchArea {
        width: parent.width;
        height: parent.height;
    }

    scope := FocusScope {
        KeyBinding {
            keys: @keys(Escape);
            activated => {
                root.close();
            }
        }

        content-layout := VerticalLayout {
            padding: 48px;
            spacing: 12px;

            Text {
                text: "About";
                font-size: 18px;
                font-weight: 700;
                color: #e0e0e0;
            }

            Rectangle {
                height: 16px;
            }

            about-texts := HorizontalLayout {
                spacing: 0px;

                VerticalLayout {
                    spacing: 6px;

                    Text {
                        text: root.version == "" ? "NInferMonitor" : "NInferMonitor v" + root.version;
                        font-size: 13px;
                        color: #e0e0e0;
                    }

                    Text {
                        text: "Copyright (C) 2026 Aleksey Sanin";
                        font-size: 12px;
                        color: #9e9e9e;
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;
                }
            }

            Rectangle {
                height: 16px;
            }

            HorizontalLayout {
                alignment: center;
                spacing: 8px;

                btn-ok := DarkButton {
                    text: "OK";
                    width: 90px;
                    height: 24px;
                    clicked => {
                        root.close();
                    }
                }
            }
        }
    }
}
